// yarn env:init helpers: fresh .env content and the completion of P1 keys in an existing file.
import { describe, expect, it } from 'vitest';
import {
  parseAllowedOrigins,
  parseSessionSecret,
} from '../../apps/api/src/modules/auth/auth-config.js';
import {
  completeP1Keys,
  DEFAULT_ALLOWED_WEB_ORIGINS,
  definedKeys,
  freshEnvContent,
  REQUIRED_KEYS,
} from '../../scripts/local/env-file.mjs';

const valueOf = (content: string, key: string) =>
  [...content.matchAll(new RegExp(`^${key}=(.*?)\\r?$`, 'gm'))].at(-1)?.[1] ?? '';

const P0_ONLY = [
  '# Local-only secrets generated by `yarn env:init`. Never commit this file.',
  'MYSQL_ROOT_PASSWORD=synthetic0root',
  'TB_DB_APP_PASSWORD=synthetic0app',
  'TB_DB_MIGRATE_PASSWORD=synthetic0migrate',
  'DATABASE_URL="mysql://tb_dev:synthetic0app@127.0.0.1:3307/tb_notice_dev"',
  '',
].join('\n');

describe('fresh .env', () => {
  it('defines every required key with values the API accepts', () => {
    const content = freshEnvContent();
    expect([...REQUIRED_KEYS].every((key) => definedKeys(content).has(key))).toBe(true);
    expect(parseSessionSecret(valueOf(content, 'TB_SESSION_SECRET'))).toHaveLength(32);
    expect([...parseAllowedOrigins(valueOf(content, 'TB_ALLOWED_WEB_ORIGINS'))]).toEqual([
      'http://localhost:5173',
      'http://127.0.0.1:5173',
    ]);
    expect(valueOf(content, 'TB_ALLOWED_WEB_ORIGINS')).toBe(DEFAULT_ALLOWED_WEB_ORIGINS);
  });

  it('generates different secrets every time', () => {
    const a = freshEnvContent();
    const b = freshEnvContent();
    for (const key of ['MYSQL_ROOT_PASSWORD', 'TB_DB_APP_PASSWORD', 'TB_SESSION_SECRET']) {
      expect(valueOf(a, key)).not.toBe(valueOf(b, key));
    }
  });
});

describe('completing an existing .env', () => {
  it('appends only the missing P1 keys and leaves existing bytes untouched', () => {
    const { content, added, replaced } = completeP1Keys(P0_ONLY);
    expect(added).toEqual(['TB_SESSION_SECRET', 'TB_ALLOWED_WEB_ORIGINS']);
    expect(replaced).toEqual([]);
    expect(content.startsWith(P0_ONLY)).toBe(true);
    expect(parseSessionSecret(valueOf(content, 'TB_SESSION_SECRET'))).toHaveLength(32);
    expect(completeP1Keys(content)).toEqual({ content, added: [], replaced: [] });
  });

  it('keeps a usable value even when the API would reject it for another reason', () => {
    const existing = `${P0_ONLY}TB_SESSION_SECRET=operator-chosen-value\n`;
    const { content, added, replaced } = completeP1Keys(existing);
    expect(added).toEqual(['TB_ALLOWED_WEB_ORIGINS']);
    expect(replaced).toEqual([]);
    expect(valueOf(content, 'TB_SESSION_SECRET')).toBe('operator-chosen-value');
  });

  it('replaces empty and placeholder P1 values in place, on the effective (last) definition only', () => {
    const lines = [
      'MYSQL_ROOT_PASSWORD=synthetic0root',
      'TB_SESSION_SECRET=REPLACE_WITH_yarn_env:init_GENERATED_VALUE',
      'TB_DB_APP_PASSWORD=synthetic0app',
      'TB_ALLOWED_WEB_ORIGINS=http://localhost:5173',
      'TB_ALLOWED_WEB_ORIGINS=""',
      '',
    ];
    const { content, added, replaced } = completeP1Keys(lines.join('\n'));
    expect(added).toEqual([]);
    expect(replaced).toEqual(['TB_SESSION_SECRET', 'TB_ALLOWED_WEB_ORIGINS']);
    const after = content.split('\n');
    expect(after).toHaveLength(lines.length);
    expect(after[0]).toBe(lines[0]);
    expect(after[2]).toBe(lines[2]);
    expect(after[3]).toBe(lines[3]); // an earlier, non-effective definition is left alone
    expect(parseSessionSecret(valueOf(content, 'TB_SESSION_SECRET'))).toHaveLength(32);
    expect(after[4]).toBe(`TB_ALLOWED_WEB_ORIGINS=${DEFAULT_ALLOWED_WEB_ORIGINS}`);
  });

  it('preserves CRLF line endings and adds a newline before appended keys when missing', () => {
    const crlf = 'A=1\r\nTB_SESSION_SECRET=\r\nB=2\r\n';
    const { content } = completeP1Keys(crlf);
    expect(content.startsWith('A=1\r\nTB_SESSION_SECRET=')).toBe(true);
    expect(content).toContain('\r\nB=2\r\n');
    expect(content.split('\n')[1]?.endsWith('\r')).toBe(true);
    expect(completeP1Keys('A=1').content.startsWith('A=1\n# P1:')).toBe(true);
  });
});
