-- TB-SCHEMA-API-v1.0.0 initial migration (P0-C4 reviewed draft; NOT YET APPLIED).
-- Generated by `prisma migrate dev --create-only` (Prisma 7.10.0) from apps/api/prisma/schema.prisma,
-- then manually augmented before first apply with MySQL semantics Prisma cannot express
-- (docs/decisions/ADR-0001-mysql-manual-migration-semantics.md,
--  docs/verification/p0/CONSTRAINT_INVENTORY.md):
--   M1  all 33 tables: ENGINE=InnoDB and COLLATE utf8mb4_0900_bin (Prisma emitted utf8mb4_unicode_ci);
--   M2  30 CHECK constraints copied verbatim (names and expressions) from the frozen
--       docs/reference/database-api-v1/.../prisma/initial-schema.preview.sql (section at end of file).
-- No other generated statement was changed.

-- CreateTable
CREATE TABLE `users` (
    `id` CHAR(36) NOT NULL,
    `email` VARCHAR(254) NOT NULL,
    `display_name` VARCHAR(160) NOT NULL,
    `password_hash` VARCHAR(255) NOT NULL,
    `enabled` BOOLEAN NOT NULL DEFAULT true,
    `session_epoch` INTEGER UNSIGNED NOT NULL DEFAULT 1,
    `password_changed_at` DATETIME(3) NULL,
    `disabled_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `users_email_key`(`email`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `auth_sessions` (
    `id` CHAR(36) NOT NULL,
    `user_id` CHAR(36) NOT NULL,
    `token_hash` VARCHAR(64) NOT NULL,
    `csrf_token_hash` VARCHAR(64) NOT NULL,
    `expires_at` DATETIME(3) NOT NULL,
    `last_seen_at` DATETIME(3) NOT NULL,
    `revoked_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `auth_sessions_token_hash_key`(`token_hash`),
    INDEX `auth_sessions_user_id_expires_at_idx`(`user_id`, `expires_at`),
    INDEX `auth_sessions_expires_at_idx`(`expires_at`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `agencies` (
    `id` CHAR(36) NOT NULL,
    `display_name` VARCHAR(200) NOT NULL,
    `legal_name` VARCHAR(255) NULL,
    `organization_type` VARCHAR(50) NULL,
    `jurisdiction_country` VARCHAR(2) NULL,
    `registration_authority` VARCHAR(200) NULL,
    `registration_number` VARCHAR(100) NULL,
    `website_url` VARCHAR(2048) NULL,
    `copyright_email` VARCHAR(254) NULL,
    `verification_email` VARCHAR(254) NULL,
    `postal_address` JSON NULL,
    `phone` VARCHAR(80) NULL,
    `drive_root_url` VARCHAR(2048) NULL,
    `master_url` VARCHAR(2048) NULL,
    `start_here_url` VARCHAR(2048) NULL,
    `field_attributions` JSON NULL,
    `record_state` ENUM('DRAFT', 'ACTIVE', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT',
    `canonical_code` VARCHAR(100) NULL,
    `canonical_source_id` CHAR(36) NULL,
    `binding_state` ENUM('LOCAL_ONLY', 'SOURCE_REFERENCED', 'DIVERGENT') NOT NULL DEFAULT 'LOCAL_ONLY',
    `notes` LONGTEXT NULL,
    `archived_at` DATETIME(3) NULL,
    `archive_reason` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `updated_by_id` CHAR(36) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `agencies_canonical_code_key`(`canonical_code`),
    INDEX `agencies_record_state_created_at_idx`(`record_state`, `created_at`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `owners` (
    `id` CHAR(36) NOT NULL,
    `display_name` VARCHAR(200) NOT NULL,
    `aliases` JSON NULL,
    `contact_name` VARCHAR(200) NULL,
    `contact_email` VARCHAR(254) NULL,
    `source_channels` JSON NULL,
    `website_url` VARCHAR(2048) NULL,
    `preferred_language` VARCHAR(20) NULL,
    `drive_folder_url` VARCHAR(2048) NULL,
    `record_state` ENUM('DRAFT', 'ACTIVE', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT',
    `canonical_code` VARCHAR(100) NULL,
    `canonical_source_id` CHAR(36) NULL,
    `binding_state` ENUM('LOCAL_ONLY', 'SOURCE_REFERENCED', 'DIVERGENT') NOT NULL DEFAULT 'LOCAL_ONLY',
    `notes` LONGTEXT NULL,
    `archived_at` DATETIME(3) NULL,
    `archive_reason` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `updated_by_id` CHAR(36) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `owners_canonical_code_key`(`canonical_code`),
    INDEX `owners_record_state_created_at_idx`(`record_state`, `created_at`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `legal_subjects` (
    `id` CHAR(36) NOT NULL,
    `subject_type` ENUM('INDIVIDUAL', 'LEGAL_ENTITY', 'OTHER') NOT NULL,
    `legal_name` VARCHAR(255) NOT NULL,
    `aliases` JSON NULL,
    `jurisdiction_country` VARCHAR(2) NULL,
    `legal_form` VARCHAR(80) NULL,
    `registration_authority` VARCHAR(200) NULL,
    `registration_number` VARCHAR(100) NULL,
    `contact_email` VARCHAR(254) NULL,
    `postal_address` JSON NULL,
    `field_attributions` JSON NULL,
    `identity_review_state` ENUM('UNREVIEWED', 'REVIEWED_WITH_LIMITS', 'CONFLICT') NOT NULL DEFAULT 'UNREVIEWED',
    `record_state` ENUM('DRAFT', 'ACTIVE', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT',
    `canonical_code` VARCHAR(100) NULL,
    `canonical_source_id` CHAR(36) NULL,
    `binding_state` ENUM('LOCAL_ONLY', 'SOURCE_REFERENCED', 'DIVERGENT') NOT NULL DEFAULT 'LOCAL_ONLY',
    `notes` LONGTEXT NULL,
    `archived_at` DATETIME(3) NULL,
    `archive_reason` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `updated_by_id` CHAR(36) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `legal_subjects_canonical_code_key`(`canonical_code`),
    INDEX `legal_subjects_legal_name_idx`(`legal_name`),
    INDEX `legal_subjects_registration_authority_registrati_902c1ede`(`registration_authority`, `registration_number`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `owner_subjects` (
    `id` CHAR(36) NOT NULL,
    `owner_id` CHAR(36) NOT NULL,
    `legal_subject_id` CHAR(36) NOT NULL,
    `relationship_label` VARCHAR(200) NULL,
    `source_id` CHAR(36) NULL,
    `link_state` ENUM('LINKED', 'PAUSED', 'UNLINKED') NOT NULL DEFAULT 'LINKED',
    `unlinked_at` DATETIME(3) NULL,
    `unlink_reason` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `updated_by_id` CHAR(36) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `owner_subjects_legal_subject_id_link_state_idx`(`legal_subject_id`, `link_state`),
    UNIQUE INDEX `owner_subjects_owner_id_legal_subject_id_key`(`owner_id`, `legal_subject_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `signers` (
    `id` CHAR(36) NOT NULL,
    `agency_id` CHAR(36) NOT NULL,
    `full_legal_name` VARCHAR(255) NOT NULL,
    `title` VARCHAR(200) NULL,
    `contact_email` VARCHAR(254) NULL,
    `identity_source_id` CHAR(36) NULL,
    `delegation_source_id` CHAR(36) NULL,
    `operational_state` ENUM('DRAFT', 'AVAILABLE', 'PAUSED', 'ENDED') NOT NULL DEFAULT 'DRAFT',
    `canonical_code` VARCHAR(100) NULL,
    `canonical_source_id` CHAR(36) NULL,
    `binding_state` ENUM('LOCAL_ONLY', 'SOURCE_REFERENCED', 'DIVERGENT') NOT NULL DEFAULT 'LOCAL_ONLY',
    `notes` LONGTEXT NULL,
    `archived_at` DATETIME(3) NULL,
    `archive_reason` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `updated_by_id` CHAR(36) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `signers_canonical_code_key`(`canonical_code`),
    INDEX `signers_agency_id_operational_state_idx`(`agency_id`, `operational_state`),
    UNIQUE INDEX `signers_id_agency_id_key`(`id`, `agency_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `routes` (
    `id` CHAR(36) NOT NULL,
    `agency_id` CHAR(36) NOT NULL,
    `owner_subject_id` CHAR(36) NOT NULL,
    `platform` ENUM('YOUTUBE') NOT NULL DEFAULT 'YOUTUBE',
    `link_state` ENUM('LINKED', 'PAUSED', 'UNLINKED') NOT NULL DEFAULT 'LINKED',
    `default_signer_id` CHAR(36) NULL,
    `preferred_coverage_id` CHAR(36) NULL,
    `case_prefix_hint` VARCHAR(40) NULL,
    `unlinked_at` DATETIME(3) NULL,
    `state_reason` LONGTEXT NULL,
    `canonical_code` VARCHAR(100) NULL,
    `canonical_source_id` CHAR(36) NULL,
    `binding_state` ENUM('LOCAL_ONLY', 'SOURCE_REFERENCED', 'DIVERGENT') NOT NULL DEFAULT 'LOCAL_ONLY',
    `notes` LONGTEXT NULL,
    `archived_at` DATETIME(3) NULL,
    `archive_reason` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `updated_by_id` CHAR(36) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `routes_canonical_code_key`(`canonical_code`),
    INDEX `routes_owner_subject_id_link_state_idx`(`owner_subject_id`, `link_state`),
    UNIQUE INDEX `routes_agency_id_owner_subject_id_platform_key`(`agency_id`, `owner_subject_id`, `platform`),
    UNIQUE INDEX `routes_id_agency_id_platform_key`(`id`, `agency_id`, `platform`),
    UNIQUE INDEX `routes_id_agency_id_key`(`id`, `agency_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `mandates` (
    `id` CHAR(36) NOT NULL,
    `agency_id` CHAR(36) NOT NULL,
    `label` VARCHAR(255) NOT NULL,
    `external_reference` VARCHAR(191) NULL,
    `description` LONGTEXT NULL,
    `canonical_code` VARCHAR(100) NULL,
    `canonical_source_id` CHAR(36) NULL,
    `binding_state` ENUM('LOCAL_ONLY', 'SOURCE_REFERENCED', 'DIVERGENT') NOT NULL DEFAULT 'LOCAL_ONLY',
    `notes` LONGTEXT NULL,
    `archived_at` DATETIME(3) NULL,
    `archive_reason` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `updated_by_id` CHAR(36) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `mandates_canonical_code_key`(`canonical_code`),
    INDEX `mandates_agency_id_created_at_idx`(`agency_id`, `created_at`),
    UNIQUE INDEX `mandates_id_agency_id_key`(`id`, `agency_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `mandate_versions` (
    `id` CHAR(36) NOT NULL,
    `mandate_id` CHAR(36) NOT NULL,
    `agency_id` CHAR(36) NOT NULL,
    `version` INTEGER UNSIGNED NOT NULL,
    `version_state` ENUM('DRAFT', 'FROZEN') NOT NULL DEFAULT 'DRAFT',
    `change_kind` ENUM('NEW_AUTHORIZATION', 'AMENDMENT', 'DOCUMENT_CAPTURE', 'METADATA_CORRECTION') NOT NULL,
    `predecessor_id` CHAR(36) NULL,
    `primary_source_id` CHAR(36) NULL,
    `additional_source_refs` JSON NULL,
    `document_state` ENUM('MISSING', 'DRAFT', 'SIGNED_APPEARING', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    `source_review_state` ENUM('UNREVIEWED', 'REVIEWED_WITH_LIMITS', 'CONFLICT') NOT NULL DEFAULT 'UNREVIEWED',
    `signed_dates_raw` JSON NULL,
    `validity_model` ENUM('UNKNOWN', 'FIXED_TERM', 'UNTIL_TERMINATED') NOT NULL DEFAULT 'UNKNOWN',
    `effective_on` DATE NULL,
    `expires_on` DATE NULL,
    `validity_notes` LONGTEXT NULL,
    `frozen_at` DATETIME(3) NULL,
    `change_reason` LONGTEXT NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `updated_by_id` CHAR(36) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `mandate_versions_mandate_id_version_key`(`mandate_id`, `version`),
    UNIQUE INDEX `mandate_versions_id_agency_id_key`(`id`, `agency_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `mandate_coverages` (
    `id` CHAR(36) NOT NULL,
    `mandate_version_id` CHAR(36) NOT NULL,
    `route_id` CHAR(36) NOT NULL,
    `agency_id` CHAR(36) NOT NULL,
    `coverage_label` VARCHAR(191) NOT NULL,
    `covered_works_scope` LONGTEXT NULL,
    `territorial_scope` LONGTEXT NULL,
    `action_scope` JSON NULL,
    `exclusions` LONGTEXT NULL,
    `conditions` LONGTEXT NULL,
    `exclusivity` ENUM('UNKNOWN', 'EXCLUSIVE', 'NON_EXCLUSIVE') NOT NULL DEFAULT 'UNKNOWN',
    `effective_on` DATE NULL,
    `expires_on` DATE NULL,
    `basis_source_id` CHAR(36) NULL,
    `predecessor_coverage_id` CHAR(36) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `updated_by_id` CHAR(36) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `mandate_coverages_route_id_mandate_version_id_co_e7b0d69b`(`route_id`, `mandate_version_id`, `coverage_label`),
    UNIQUE INDEX `mandate_coverages_id_agency_id_key`(`id`, `agency_id`),
    UNIQUE INDEX `mandate_coverages_id_route_id_agency_id_key`(`id`, `route_id`, `agency_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `coverage_signers` (
    `id` CHAR(36) NOT NULL,
    `coverage_id` CHAR(36) NOT NULL,
    `agency_id` CHAR(36) NOT NULL,
    `signer_id` CHAR(36) NOT NULL,
    `capacity` VARCHAR(120) NOT NULL,
    `action_scope` JSON NULL,
    `source_id` CHAR(36) NULL,
    `effective_on` DATE NULL,
    `ends_on` DATE NULL,
    `limitations` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `updated_by_id` CHAR(36) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `coverage_signers_coverage_id_signer_id_capacity_key`(`coverage_id`, `signer_id`, `capacity`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `authority_events` (
    `id` CHAR(36) NOT NULL,
    `mandate_id` CHAR(36) NOT NULL,
    `agency_id` CHAR(36) NOT NULL,
    `coverage_id` CHAR(36) NULL,
    `event_type` ENUM('CURRENTNESS_RECORDED', 'REVOCATION', 'TERMINATION', 'SUPERSESSION', 'RESIGNATION', 'CORRECTION') NOT NULL,
    `source_id` CHAR(36) NOT NULL,
    `provenance` ENUM('DOCUMENT_REVIEWED', 'OPERATOR_REPORTED', 'ANALYSIS', 'MISSING', 'CONFLICT') NOT NULL,
    `effective_on` DATE NULL,
    `effective_at` DATETIME(3) NULL,
    `raw_effective_text` VARCHAR(500) NULL,
    `scope_text` LONGTEXT NOT NULL,
    `supersedes_event_id` CHAR(36) NULL,
    `interpretation` LONGTEXT NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,

    UNIQUE INDEX `authority_events_supersedes_event_id_key`(`supersedes_event_id`),
    INDEX `authority_events_mandate_id_created_at_idx`(`mandate_id`, `created_at`),
    INDEX `authority_events_coverage_id_created_at_idx`(`coverage_id`, `created_at`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `cases` (
    `id` CHAR(36) NOT NULL,
    `agency_id` CHAR(36) NOT NULL,
    `platform` ENUM('YOUTUBE') NOT NULL DEFAULT 'YOUTUBE',
    `intake_label` VARCHAR(255) NOT NULL,
    `owner_hint_id` CHAR(36) NULL,
    `route_id` CHAR(36) NULL,
    `canonical_case_id` VARCHAR(100) NULL,
    `canonical_binding_source_id` CHAR(36) NULL,
    `case_class` ENUM('WORKING_INTAKE', 'CURRENT_OPERATION', 'RECOVERED_HISTORY', 'EXTERNAL_REFERENCE') NOT NULL DEFAULT 'WORKING_INTAKE',
    `workflow_state` ENUM('INTAKE', 'PREPARING', 'DRAFTING', 'AWAITING_HUMAN', 'AWAITING_PLATFORM', 'CLOSED') NOT NULL DEFAULT 'INTAKE',
    `current_authority_selection_id` CHAR(36) NULL,
    `packet_source_id` CHAR(36) NULL,
    `drive_folder_url` VARCHAR(2048) NULL,
    `context_revision` INTEGER UNSIGNED NOT NULL DEFAULT 1,
    `closed_at` DATETIME(3) NULL,
    `close_reason` LONGTEXT NULL,
    `archived_at` DATETIME(3) NULL,
    `archive_reason` LONGTEXT NULL,
    `notes` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `updated_by_id` CHAR(36) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `cases_canonical_case_id_key`(`canonical_case_id`),
    INDEX `cases_agency_id_workflow_state_created_at_id_idx`(`agency_id`, `workflow_state`, `created_at`, `id`),
    INDEX `cases_route_id_created_at_id_idx`(`route_id`, `created_at`, `id`),
    UNIQUE INDEX `cases_id_agency_id_key`(`id`, `agency_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `case_authority_selections` (
    `id` CHAR(36) NOT NULL,
    `case_id` CHAR(36) NOT NULL,
    `agency_id` CHAR(36) NOT NULL,
    `route_id` CHAR(36) NOT NULL,
    `signer_id` CHAR(36) NOT NULL,
    `task_type` ENUM('INITIAL', 'NMI_REPLY') NOT NULL,
    `intended_from_email` VARCHAR(254) NOT NULL,
    `basis_source_id` CHAR(36) NULL,
    `selection_note` LONGTEXT NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,

    INDEX `case_authority_selections_case_id_created_at_idx`(`case_id`, `created_at`),
    UNIQUE INDEX `case_authority_selections_id_case_id_key`(`id`, `case_id`),
    UNIQUE INDEX `case_authority_selections_id_case_id_agency_id_route_id_key`(`id`, `case_id`, `agency_id`, `route_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `case_authority_coverages` (
    `id` CHAR(36) NOT NULL,
    `selection_id` CHAR(36) NOT NULL,
    `case_id` CHAR(36) NOT NULL,
    `agency_id` CHAR(36) NOT NULL,
    `route_id` CHAR(36) NOT NULL,
    `coverage_id` CHAR(36) NOT NULL,
    `application_scope` LONGTEXT NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,

    UNIQUE INDEX `case_authority_coverages_selection_id_coverage_id_key`(`selection_id`, `coverage_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `reported_items` (
    `id` CHAR(36) NOT NULL,
    `case_id` CHAR(36) NOT NULL,
    `raw_url` VARCHAR(4096) NOT NULL,
    `normalized_url` VARCHAR(2048) NOT NULL,
    `external_item_id` VARCHAR(64) NOT NULL,
    `display_title` VARCHAR(500) NULL,
    `observed_at` DATETIME(3) NULL,
    `archived_at` DATETIME(3) NULL,
    `archive_reason` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `updated_by_id` CHAR(36) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `reported_items_external_item_id_idx`(`external_item_id`),
    UNIQUE INDEX `reported_items_case_id_external_item_id_key`(`case_id`, `external_item_id`),
    UNIQUE INDEX `reported_items_id_case_id_key`(`id`, `case_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `case_works` (
    `id` CHAR(36) NOT NULL,
    `case_id` CHAR(36) NOT NULL,
    `title` VARCHAR(500) NOT NULL,
    `source_url` VARCHAR(4096) NULL,
    `external_work_id` VARCHAR(191) NULL,
    `work_type` VARCHAR(100) NULL,
    `notes` LONGTEXT NULL,
    `archived_at` DATETIME(3) NULL,
    `archive_reason` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `updated_by_id` CHAR(36) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `case_works_case_id_created_at_idx`(`case_id`, `created_at`),
    UNIQUE INDEX `case_works_id_case_id_key`(`id`, `case_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `use_mappings` (
    `id` CHAR(36) NOT NULL,
    `case_id` CHAR(36) NOT NULL,
    `case_work_id` CHAR(36) NOT NULL,
    `reported_item_id` CHAR(36) NOT NULL,
    `occurrence` INTEGER UNSIGNED NOT NULL,
    `source_start_ms` BIGINT UNSIGNED NULL,
    `source_end_ms` BIGINT UNSIGNED NULL,
    `reported_start_ms` BIGINT UNSIGNED NULL,
    `reported_end_ms` BIGINT UNSIGNED NULL,
    `raw_timecodes` JSON NULL,
    `boundary_convention` VARCHAR(40) NOT NULL DEFAULT 'UNKNOWN',
    `provenance` ENUM('DOCUMENT_REVIEWED', 'OPERATOR_REPORTED', 'ANALYSIS', 'MISSING', 'CONFLICT') NOT NULL DEFAULT 'MISSING',
    `basis_source_id` CHAR(36) NULL,
    `limitations` LONGTEXT NULL,
    `archived_at` DATETIME(3) NULL,
    `archive_reason` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `updated_by_id` CHAR(36) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `use_mappings_reported_item_id_case_id_idx`(`reported_item_id`, `case_id`),
    UNIQUE INDEX `use_mappings_case_work_id_reported_item_id_occurrence_key`(`case_work_id`, `reported_item_id`, `occurrence`),
    UNIQUE INDEX `use_mappings_id_case_id_key`(`id`, `case_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `source_references` (
    `id` CHAR(36) NOT NULL,
    `agency_id` CHAR(36) NULL,
    `source_group_id` CHAR(36) NOT NULL,
    `revision` INTEGER UNSIGNED NOT NULL,
    `supersedes_source_id` CHAR(36) NULL,
    `title` VARCHAR(500) NOT NULL,
    `canonical_url` VARCHAR(4096) NULL,
    `provider_file_id` VARCHAR(191) NULL,
    `provider_revision_id` VARCHAR(191) NULL,
    `source_role` ENUM('CANONICAL_RECORD', 'PRIMARY_CORRESPONDENCE', 'OPERATOR_INPUT', 'DERIVED_DRAFT', 'EXTERNAL_REFERENCE', 'POLICY_REFERENCE') NOT NULL,
    `access_state` ENUM('NOT_CHECKED', 'ACCESSIBLE_AT_CHECK', 'UNAVAILABLE_AT_CHECK') NOT NULL DEFAULT 'NOT_CHECKED',
    `content_sha256` VARCHAR(64) NULL,
    `hash_target` ENUM('RAW_FILE', 'EXTRACTED_TEXT', 'OTHER') NULL,
    `reported_provenance` ENUM('DOCUMENT_REVIEWED', 'OPERATOR_REPORTED', 'ANALYSIS', 'MISSING', 'CONFLICT') NOT NULL DEFAULT 'OPERATOR_REPORTED',
    `raw_provenance` VARCHAR(120) NULL,
    `scope_text` LONGTEXT NOT NULL,
    `scope_bindings` JSON NULL,
    `observed_at` DATETIME(3) NULL,
    `reviewed_by_label` VARCHAR(255) NULL,
    `reviewed_at` DATETIME(3) NULL,
    `excerpt` LONGTEXT NULL,
    `excerpt_locator` VARCHAR(500) NULL,
    `limitations` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,

    UNIQUE INDEX `source_references_supersedes_source_id_key`(`supersedes_source_id`),
    INDEX `source_references_agency_id_created_at_idx`(`agency_id`, `created_at`),
    INDEX `source_references_provider_file_id_idx`(`provider_file_id`),
    UNIQUE INDEX `source_references_source_group_id_revision_key`(`source_group_id`, `revision`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `case_sources` (
    `id` CHAR(36) NOT NULL,
    `case_id` CHAR(36) NOT NULL,
    `source_id` CHAR(36) NOT NULL,
    `use_role` VARCHAR(60) NOT NULL,
    `scope_note` LONGTEXT NOT NULL,
    `link_state` ENUM('LINKED', 'PAUSED', 'UNLINKED') NOT NULL DEFAULT 'LINKED',
    `state_reason` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `updated_by_id` CHAR(36) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `case_sources_source_id_idx`(`source_id`),
    UNIQUE INDEX `case_sources_case_id_source_id_use_role_key`(`case_id`, `source_id`, `use_role`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `case_facts` (
    `id` CHAR(36) NOT NULL,
    `case_id` CHAR(36) NOT NULL,
    `fact_group_id` CHAR(36) NOT NULL,
    `revision` INTEGER UNSIGNED NOT NULL,
    `supersedes_fact_id` CHAR(36) NULL,
    `fact_type` ENUM('RIGHTS_BASIS', 'RIGHTS_SCOPE', 'PERMISSION', 'AV_COMPARISON', 'EXCEPTION_REVIEW', 'WORK_IDENTIFICATION', 'REPORTED_IDENTIFICATION', 'DUPLICATE_REVIEW', 'AUTHORITY_CURRENTNESS') NOT NULL,
    `scope_kind` ENUM('CASE', 'WORK', 'REPORTED_ITEM', 'USE') NOT NULL,
    `case_work_id` CHAR(36) NULL,
    `reported_item_id` CHAR(36) NULL,
    `mapping_id` CHAR(36) NULL,
    `value` JSON NOT NULL,
    `provenance` ENUM('DOCUMENT_REVIEWED', 'OPERATOR_REPORTED', 'ANALYSIS', 'MISSING', 'CONFLICT') NOT NULL,
    `raw_provenance` VARCHAR(120) NULL,
    `resolution_state` ENUM('UNASSESSED', 'SUPPORTED_FOR_SCOPE', 'CONFLICT', 'WITHDRAWN') NOT NULL DEFAULT 'UNASSESSED',
    `asserted_by_label` VARCHAR(255) NULL,
    `asserted_as_of` DATETIME(3) NULL,
    `scope_text` LONGTEXT NOT NULL,
    `limitations` LONGTEXT NULL,
    `change_reason` LONGTEXT NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,

    UNIQUE INDEX `case_facts_supersedes_fact_id_key`(`supersedes_fact_id`),
    INDEX `case_facts_case_id_fact_type_created_at_idx`(`case_id`, `fact_type`, `created_at`),
    UNIQUE INDEX `case_facts_fact_group_id_revision_key`(`fact_group_id`, `revision`),
    UNIQUE INDEX `case_facts_id_case_id_key`(`id`, `case_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `fact_sources` (
    `id` CHAR(36) NOT NULL,
    `fact_id` CHAR(36) NOT NULL,
    `case_source_id` CHAR(36) NOT NULL,
    `support_role` VARCHAR(80) NOT NULL,
    `supported_assertion` LONGTEXT NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,

    UNIQUE INDEX `fact_sources_fact_id_case_source_id_support_role_key`(`fact_id`, `case_source_id`, `support_role`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `correspondence` (
    `id` CHAR(36) NOT NULL,
    `agency_id` CHAR(36) NOT NULL,
    `mailbox_address` VARCHAR(254) NOT NULL,
    `direction` ENUM('INBOUND', 'OUTBOUND') NOT NULL,
    `subject` VARCHAR(998) NOT NULL,
    `message_id` VARCHAR(998) NULL,
    `in_reply_to` VARCHAR(998) NULL,
    `references` JSON NULL,
    `source_identity_hash` VARCHAR(64) NULL,
    `capture_mode` ENUM('RAW_SOURCE', 'COPIED_FULL_TEXT', 'EXCERPT', 'OPERATOR_REPORTED') NOT NULL,
    `body_role` ENUM('FULL_MESSAGE', 'AUTHORED_BODY', 'QUOTED_HISTORY', 'EXCERPT', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    `body_text` LONGTEXT NULL,
    `body_sha256` VARCHAR(64) NULL,
    `raw_source_id` CHAR(36) NULL,
    `attachments_manifest` JSON NULL,
    `header_date_raw` VARCHAR(255) NULL,
    `occurred_at` DATETIME(3) NULL,
    `timestamp_precision` VARCHAR(40) NOT NULL DEFAULT 'UNKNOWN',
    `from_address` VARCHAR(254) NULL,
    `to_address` VARCHAR(254) NULL,
    `reply_to_address` VARCHAR(254) NULL,
    `limitations` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,

    INDEX `correspondence_agency_id_occurred_at_id_idx`(`agency_id`, `occurred_at`, `id`),
    UNIQUE INDEX `correspondence_agency_id_mailbox_address_source__77ddb99b`(`agency_id`, `mailbox_address`, `source_identity_hash`),
    UNIQUE INDEX `correspondence_id_agency_id_key`(`id`, `agency_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `correspondence_bindings` (
    `id` CHAR(36) NOT NULL,
    `case_id` CHAR(36) NOT NULL,
    `agency_id` CHAR(36) NOT NULL,
    `correspondence_id` CHAR(36) NOT NULL,
    `reported_item_id` CHAR(36) NULL,
    `event_type` ENUM('INITIAL_AS_SENT', 'ACK', 'NMI', 'REPLY_AS_SENT', 'SUPPLEMENT_AS_SENT', 'CORRECTION_AS_SENT', 'OUTCOME', 'OTHER') NOT NULL,
    `platform_reference` VARCHAR(191) NULL,
    `outcome` ENUM('REMOVED', 'REINSTATED', 'REJECTED', 'RETRACTED', 'OTHER') NULL,
    `interpretation` LONGTEXT NULL,
    `supersedes_binding_id` CHAR(36) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,

    UNIQUE INDEX `correspondence_bindings_supersedes_binding_id_key`(`supersedes_binding_id`),
    INDEX `correspondence_bindings_case_id_created_at_idx`(`case_id`, `created_at`),
    INDEX `correspondence_bindings_correspondence_id_idx`(`correspondence_id`),
    INDEX `correspondence_bindings_platform_reference_idx`(`platform_reference`),
    UNIQUE INDEX `correspondence_bindings_id_case_id_key`(`id`, `case_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `prompt_snapshots` (
    `id` CHAR(36) NOT NULL,
    `case_id` CHAR(36) NOT NULL,
    `task_type` ENUM('INITIAL', 'NMI_REPLY') NOT NULL,
    `generation_mode` ENUM('PREPARATION', 'DRAFTING') NOT NULL,
    `version` INTEGER UNSIGNED NOT NULL,
    `authority_selection_id` CHAR(36) NULL,
    `parent_binding_id` CHAR(36) NULL,
    `contract_version` VARCHAR(80) NOT NULL,
    `template_version` VARCHAR(80) NOT NULL,
    `context_revision` INTEGER UNSIGNED NOT NULL,
    `dependency_digest` VARCHAR(64) NOT NULL,
    `dependency_manifest` JSON NOT NULL,
    `context_json` JSON NOT NULL,
    `source_manifest` JSON NOT NULL,
    `missing_items` JSON NOT NULL,
    `conflicts` JSON NOT NULL,
    `rendered_prompt` LONGTEXT NOT NULL,
    `prompt_sha256` VARCHAR(64) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,

    INDEX `prompt_snapshots_case_id_created_at_idx`(`case_id`, `created_at`),
    UNIQUE INDEX `prompt_snapshots_case_id_task_type_version_key`(`case_id`, `task_type`, `version`),
    UNIQUE INDEX `prompt_snapshots_id_case_id_key`(`id`, `case_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `notice_candidates` (
    `id` CHAR(36) NOT NULL,
    `case_id` CHAR(36) NOT NULL,
    `prompt_snapshot_id` CHAR(36) NOT NULL,
    `parent_candidate_id` CHAR(36) NULL,
    `version` INTEGER UNSIGNED NOT NULL,
    `task_type` ENUM('INITIAL', 'NMI_REPLY') NOT NULL,
    `subject` VARCHAR(998) NOT NULL,
    `envelope_json` JSON NOT NULL,
    `body_text` LONGTEXT NOT NULL,
    `body_sha256` VARCHAR(64) NOT NULL,
    `artifact_sha256` VARCHAR(64) NOT NULL,
    `prepared_documents` JSON NOT NULL,
    `signature_state` VARCHAR(40) NOT NULL DEFAULT 'HUMAN_PENDING',
    `authoring_tool` VARCHAR(100) NULL,
    `revision_reason` LONGTEXT NULL,
    `superseded_at` DATETIME(3) NULL,
    `supersede_reason` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,

    INDEX `notice_candidates_case_id_created_at_idx`(`case_id`, `created_at`),
    UNIQUE INDEX `notice_candidates_case_id_task_type_version_key`(`case_id`, `task_type`, `version`),
    UNIQUE INDEX `notice_candidates_id_case_id_key`(`id`, `case_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `validation_runs` (
    `id` CHAR(36) NOT NULL,
    `candidate_id` CHAR(36) NOT NULL,
    `case_id` CHAR(36) NOT NULL,
    `artifact_sha256` VARCHAR(64) NOT NULL,
    `dependency_digest` VARCHAR(64) NOT NULL,
    `dependency_manifest` JSON NOT NULL,
    `evaluated_context_json` JSON NOT NULL,
    `ruleset_version` VARCHAR(80) NOT NULL,
    `result` ENUM('TECHNICAL_PASS', 'BLOCKED', 'REVIEW_REQUIRED', 'ERROR') NOT NULL,
    `coverage_manifest` JSON NOT NULL,
    `blocker_count` INTEGER UNSIGNED NOT NULL,
    `review_required_count` INTEGER UNSIGNED NOT NULL,
    `warning_count` INTEGER UNSIGNED NOT NULL,
    `started_at` DATETIME(3) NOT NULL,
    `completed_at` DATETIME(3) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,

    INDEX `validation_runs_candidate_id_created_at_idx`(`candidate_id`, `created_at`),
    UNIQUE INDEX `validation_runs_id_candidate_id_key`(`id`, `candidate_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `validation_issues` (
    `id` CHAR(36) NOT NULL,
    `run_id` CHAR(36) NOT NULL,
    `rule_id` VARCHAR(100) NOT NULL,
    `check_kind` ENUM('DETERMINISTIC', 'HEURISTIC') NOT NULL,
    `severity` ENUM('BLOCKER', 'REVIEW_REQUIRED', 'WARNING', 'INFO') NOT NULL,
    `field_path` VARCHAR(500) NULL,
    `message` LONGTEXT NOT NULL,
    `details` JSON NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,

    INDEX `validation_issues_run_id_severity_idx`(`run_id`, `severity`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `candidate_assessments` (
    `id` CHAR(36) NOT NULL,
    `candidate_id` CHAR(36) NOT NULL,
    `case_id` CHAR(36) NOT NULL,
    `gate` ENUM('G1', 'G2', 'G3', 'G4', 'G5', 'G6') NOT NULL,
    `result` ENUM('PASS', 'HOLD', 'BLOCKED', 'MISSING', 'CONFLICT') NOT NULL,
    `artifact_sha256` VARCHAR(64) NOT NULL,
    `dependency_digest` VARCHAR(64) NOT NULL,
    `ruleset_version` VARCHAR(80) NOT NULL,
    `scope_state` ENUM('RECORDED_NOT_ADOPTED', 'SCOPE_CONFIRMED_FOR_CANDIDATE') NOT NULL DEFAULT 'RECORDED_NOT_ADOPTED',
    `performer_kind` ENUM('HUMAN', 'AI_ASSISTED', 'DOCUMENTED_EXTERNAL_REVIEW') NOT NULL,
    `performer_label` VARCHAR(255) NOT NULL,
    `assessed_at` DATETIME(3) NULL,
    `provenance` ENUM('DOCUMENT_REVIEWED', 'OPERATOR_REPORTED', 'ANALYSIS', 'MISSING', 'CONFLICT') NOT NULL,
    `rationale` LONGTEXT NOT NULL,
    `scope_text` LONGTEXT NOT NULL,
    `limitations` LONGTEXT NULL,
    `ask_dispositions` JSON NULL,
    `supersedes_assessment_id` CHAR(36) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,

    UNIQUE INDEX `candidate_assessments_supersedes_assessment_id_key`(`supersedes_assessment_id`),
    INDEX `candidate_assessments_candidate_id_gate_created_at_idx`(`candidate_id`, `gate`, `created_at`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `assessment_sources` (
    `id` CHAR(36) NOT NULL,
    `assessment_id` CHAR(36) NOT NULL,
    `case_source_id` CHAR(36) NOT NULL,
    `supported_conclusion` LONGTEXT NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by_id` CHAR(36) NOT NULL,

    UNIQUE INDEX `assessment_sources_assessment_id_case_source_id_key`(`assessment_id`, `case_source_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `audit_events` (
    `id` CHAR(36) NOT NULL,
    `actor_user_id` CHAR(36) NULL,
    `request_id` VARCHAR(100) NOT NULL,
    `action` VARCHAR(120) NOT NULL,
    `entity_type` VARCHAR(100) NOT NULL,
    `entity_id` CHAR(36) NULL,
    `before_redacted` JSON NULL,
    `after_redacted` JSON NULL,
    `reason` LONGTEXT NULL,
    `source_ids` JSON NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `audit_events_entity_type_entity_id_created_at_id_idx`(`entity_type`, `entity_id`, `created_at`, `id`),
    INDEX `audit_events_actor_user_id_created_at_idx`(`actor_user_id`, `created_at`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- CreateTable
CREATE TABLE `idempotency_records` (
    `id` CHAR(36) NOT NULL,
    `actor_user_id` CHAR(36) NOT NULL,
    `operation_id` VARCHAR(100) NOT NULL,
    `idempotency_key` VARCHAR(100) NOT NULL,
    `request_sha256` VARCHAR(64) NOT NULL,
    `state` ENUM('IN_PROGRESS', 'COMPLETED') NOT NULL,
    `response_status` SMALLINT UNSIGNED NULL,
    `response_json` JSON NULL,
    `resource_type` VARCHAR(100) NULL,
    `resource_id` CHAR(36) NULL,
    `expires_at` DATETIME(3) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `idempotency_records_expires_at_idx`(`expires_at`),
    UNIQUE INDEX `idempotency_records_actor_user_id_operation_id_i_92ad1804`(`actor_user_id`, `operation_id`, `idempotency_key`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin;

-- AddForeignKey
ALTER TABLE `auth_sessions` ADD CONSTRAINT `fk_auth_sessions_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `agencies` ADD CONSTRAINT `fk_agencies_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `agencies` ADD CONSTRAINT `fk_agencies_updated_by` FOREIGN KEY (`updated_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `agencies` ADD CONSTRAINT `fk_agencies_canonical_source` FOREIGN KEY (`canonical_source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `owners` ADD CONSTRAINT `fk_owners_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `owners` ADD CONSTRAINT `fk_owners_updated_by` FOREIGN KEY (`updated_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `owners` ADD CONSTRAINT `fk_owners_canonical_source` FOREIGN KEY (`canonical_source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `legal_subjects` ADD CONSTRAINT `fk_legal_subjects_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `legal_subjects` ADD CONSTRAINT `fk_legal_subjects_updated_by` FOREIGN KEY (`updated_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `legal_subjects` ADD CONSTRAINT `fk_legal_subjects_canonical_source` FOREIGN KEY (`canonical_source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `owner_subjects` ADD CONSTRAINT `fk_owner_subjects_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `owner_subjects` ADD CONSTRAINT `fk_owner_subjects_updated_by` FOREIGN KEY (`updated_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `owner_subjects` ADD CONSTRAINT `fk_owner_subjects_owner` FOREIGN KEY (`owner_id`) REFERENCES `owners`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `owner_subjects` ADD CONSTRAINT `fk_owner_subjects_legal_subject` FOREIGN KEY (`legal_subject_id`) REFERENCES `legal_subjects`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `owner_subjects` ADD CONSTRAINT `fk_owner_subjects_source` FOREIGN KEY (`source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `signers` ADD CONSTRAINT `fk_signers_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `signers` ADD CONSTRAINT `fk_signers_updated_by` FOREIGN KEY (`updated_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `signers` ADD CONSTRAINT `fk_signers_agency` FOREIGN KEY (`agency_id`) REFERENCES `agencies`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `signers` ADD CONSTRAINT `fk_signers_identity_source` FOREIGN KEY (`identity_source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `signers` ADD CONSTRAINT `fk_signers_delegation_source` FOREIGN KEY (`delegation_source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `signers` ADD CONSTRAINT `fk_signers_canonical_source` FOREIGN KEY (`canonical_source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `routes` ADD CONSTRAINT `fk_routes_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `routes` ADD CONSTRAINT `fk_routes_updated_by` FOREIGN KEY (`updated_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `routes` ADD CONSTRAINT `fk_routes_agency` FOREIGN KEY (`agency_id`) REFERENCES `agencies`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `routes` ADD CONSTRAINT `fk_routes_owner_subject` FOREIGN KEY (`owner_subject_id`) REFERENCES `owner_subjects`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `routes` ADD CONSTRAINT `fk_routes_default_signer` FOREIGN KEY (`default_signer_id`, `agency_id`) REFERENCES `signers`(`id`, `agency_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `routes` ADD CONSTRAINT `fk_routes_preferred_coverage` FOREIGN KEY (`preferred_coverage_id`) REFERENCES `mandate_coverages`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `routes` ADD CONSTRAINT `fk_routes_canonical_source` FOREIGN KEY (`canonical_source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `mandates` ADD CONSTRAINT `fk_mandates_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `mandates` ADD CONSTRAINT `fk_mandates_updated_by` FOREIGN KEY (`updated_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `mandates` ADD CONSTRAINT `fk_mandates_agency` FOREIGN KEY (`agency_id`) REFERENCES `agencies`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `mandates` ADD CONSTRAINT `fk_mandates_canonical_source` FOREIGN KEY (`canonical_source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `mandate_versions` ADD CONSTRAINT `fk_mandate_versions_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `mandate_versions` ADD CONSTRAINT `fk_mandate_versions_updated_by` FOREIGN KEY (`updated_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `mandate_versions` ADD CONSTRAINT `fk_mandate_versions_mandate` FOREIGN KEY (`mandate_id`, `agency_id`) REFERENCES `mandates`(`id`, `agency_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `mandate_versions` ADD CONSTRAINT `fk_mandate_versions_predecessor` FOREIGN KEY (`predecessor_id`) REFERENCES `mandate_versions`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `mandate_versions` ADD CONSTRAINT `fk_mandate_versions_primary_source` FOREIGN KEY (`primary_source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `mandate_coverages` ADD CONSTRAINT `fk_mandate_coverages_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `mandate_coverages` ADD CONSTRAINT `fk_mandate_coverages_updated_by` FOREIGN KEY (`updated_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `mandate_coverages` ADD CONSTRAINT `fk_mandate_coverages_version` FOREIGN KEY (`mandate_version_id`, `agency_id`) REFERENCES `mandate_versions`(`id`, `agency_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `mandate_coverages` ADD CONSTRAINT `fk_mandate_coverages_route` FOREIGN KEY (`route_id`, `agency_id`) REFERENCES `routes`(`id`, `agency_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `mandate_coverages` ADD CONSTRAINT `fk_mandate_coverages_basis_source` FOREIGN KEY (`basis_source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `mandate_coverages` ADD CONSTRAINT `fk_mandate_coverages_predecessor_coverage` FOREIGN KEY (`predecessor_coverage_id`) REFERENCES `mandate_coverages`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `coverage_signers` ADD CONSTRAINT `fk_coverage_signers_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `coverage_signers` ADD CONSTRAINT `fk_coverage_signers_updated_by` FOREIGN KEY (`updated_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `coverage_signers` ADD CONSTRAINT `fk_coverage_signers_coverage` FOREIGN KEY (`coverage_id`, `agency_id`) REFERENCES `mandate_coverages`(`id`, `agency_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `coverage_signers` ADD CONSTRAINT `fk_coverage_signers_signer` FOREIGN KEY (`signer_id`, `agency_id`) REFERENCES `signers`(`id`, `agency_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `coverage_signers` ADD CONSTRAINT `fk_coverage_signers_source` FOREIGN KEY (`source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `authority_events` ADD CONSTRAINT `fk_authority_events_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `authority_events` ADD CONSTRAINT `fk_authority_events_mandate` FOREIGN KEY (`mandate_id`, `agency_id`) REFERENCES `mandates`(`id`, `agency_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `authority_events` ADD CONSTRAINT `fk_authority_events_coverage` FOREIGN KEY (`coverage_id`, `agency_id`) REFERENCES `mandate_coverages`(`id`, `agency_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `authority_events` ADD CONSTRAINT `fk_authority_events_source` FOREIGN KEY (`source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `authority_events` ADD CONSTRAINT `fk_authority_events_supersedes_event` FOREIGN KEY (`supersedes_event_id`) REFERENCES `authority_events`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `cases` ADD CONSTRAINT `fk_cases_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `cases` ADD CONSTRAINT `fk_cases_updated_by` FOREIGN KEY (`updated_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `cases` ADD CONSTRAINT `fk_cases_agency` FOREIGN KEY (`agency_id`) REFERENCES `agencies`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `cases` ADD CONSTRAINT `fk_cases_owner_hint` FOREIGN KEY (`owner_hint_id`) REFERENCES `owners`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `cases` ADD CONSTRAINT `fk_cases_route` FOREIGN KEY (`route_id`, `agency_id`, `platform`) REFERENCES `routes`(`id`, `agency_id`, `platform`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `cases` ADD CONSTRAINT `fk_cases_current_authority_selection` FOREIGN KEY (`current_authority_selection_id`) REFERENCES `case_authority_selections`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `cases` ADD CONSTRAINT `fk_cases_packet_source` FOREIGN KEY (`packet_source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `cases` ADD CONSTRAINT `fk_cases_canonical_binding_source` FOREIGN KEY (`canonical_binding_source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_authority_selections` ADD CONSTRAINT `fk_case_authority_selections_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_authority_selections` ADD CONSTRAINT `fk_case_authority_selections_case_record` FOREIGN KEY (`case_id`, `agency_id`) REFERENCES `cases`(`id`, `agency_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_authority_selections` ADD CONSTRAINT `fk_case_authority_selections_route` FOREIGN KEY (`route_id`, `agency_id`) REFERENCES `routes`(`id`, `agency_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_authority_selections` ADD CONSTRAINT `fk_case_authority_selections_signer` FOREIGN KEY (`signer_id`, `agency_id`) REFERENCES `signers`(`id`, `agency_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_authority_selections` ADD CONSTRAINT `fk_case_authority_selections_basis_source` FOREIGN KEY (`basis_source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_authority_coverages` ADD CONSTRAINT `fk_case_authority_coverages_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_authority_coverages` ADD CONSTRAINT `fk_case_authority_coverages_selection` FOREIGN KEY (`selection_id`, `case_id`, `agency_id`, `route_id`) REFERENCES `case_authority_selections`(`id`, `case_id`, `agency_id`, `route_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_authority_coverages` ADD CONSTRAINT `fk_case_authority_coverages_coverage` FOREIGN KEY (`coverage_id`, `route_id`, `agency_id`) REFERENCES `mandate_coverages`(`id`, `route_id`, `agency_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `reported_items` ADD CONSTRAINT `fk_reported_items_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `reported_items` ADD CONSTRAINT `fk_reported_items_updated_by` FOREIGN KEY (`updated_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `reported_items` ADD CONSTRAINT `fk_reported_items_case_record` FOREIGN KEY (`case_id`) REFERENCES `cases`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_works` ADD CONSTRAINT `fk_case_works_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_works` ADD CONSTRAINT `fk_case_works_updated_by` FOREIGN KEY (`updated_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_works` ADD CONSTRAINT `fk_case_works_case_record` FOREIGN KEY (`case_id`) REFERENCES `cases`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `use_mappings` ADD CONSTRAINT `fk_use_mappings_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `use_mappings` ADD CONSTRAINT `fk_use_mappings_updated_by` FOREIGN KEY (`updated_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `use_mappings` ADD CONSTRAINT `fk_use_mappings_case_record` FOREIGN KEY (`case_id`) REFERENCES `cases`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `use_mappings` ADD CONSTRAINT `fk_use_mappings_work` FOREIGN KEY (`case_work_id`, `case_id`) REFERENCES `case_works`(`id`, `case_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `use_mappings` ADD CONSTRAINT `fk_use_mappings_reported_item` FOREIGN KEY (`reported_item_id`, `case_id`) REFERENCES `reported_items`(`id`, `case_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `use_mappings` ADD CONSTRAINT `fk_use_mappings_basis_source` FOREIGN KEY (`basis_source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `source_references` ADD CONSTRAINT `fk_source_references_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `source_references` ADD CONSTRAINT `fk_source_references_agency` FOREIGN KEY (`agency_id`) REFERENCES `agencies`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `source_references` ADD CONSTRAINT `fk_source_references_supersedes_source` FOREIGN KEY (`supersedes_source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_sources` ADD CONSTRAINT `fk_case_sources_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_sources` ADD CONSTRAINT `fk_case_sources_updated_by` FOREIGN KEY (`updated_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_sources` ADD CONSTRAINT `fk_case_sources_case_record` FOREIGN KEY (`case_id`) REFERENCES `cases`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_sources` ADD CONSTRAINT `fk_case_sources_source` FOREIGN KEY (`source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_facts` ADD CONSTRAINT `fk_case_facts_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_facts` ADD CONSTRAINT `fk_case_facts_case_record` FOREIGN KEY (`case_id`) REFERENCES `cases`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_facts` ADD CONSTRAINT `fk_case_facts_work` FOREIGN KEY (`case_work_id`, `case_id`) REFERENCES `case_works`(`id`, `case_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_facts` ADD CONSTRAINT `fk_case_facts_reported_item` FOREIGN KEY (`reported_item_id`, `case_id`) REFERENCES `reported_items`(`id`, `case_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_facts` ADD CONSTRAINT `fk_case_facts_mapping` FOREIGN KEY (`mapping_id`, `case_id`) REFERENCES `use_mappings`(`id`, `case_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `case_facts` ADD CONSTRAINT `fk_case_facts_supersedes_fact` FOREIGN KEY (`supersedes_fact_id`) REFERENCES `case_facts`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `fact_sources` ADD CONSTRAINT `fk_fact_sources_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `fact_sources` ADD CONSTRAINT `fk_fact_sources_fact` FOREIGN KEY (`fact_id`) REFERENCES `case_facts`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `fact_sources` ADD CONSTRAINT `fk_fact_sources_case_source` FOREIGN KEY (`case_source_id`) REFERENCES `case_sources`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `correspondence` ADD CONSTRAINT `fk_correspondence_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `correspondence` ADD CONSTRAINT `fk_correspondence_agency` FOREIGN KEY (`agency_id`) REFERENCES `agencies`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `correspondence` ADD CONSTRAINT `fk_correspondence_raw_source` FOREIGN KEY (`raw_source_id`) REFERENCES `source_references`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `correspondence_bindings` ADD CONSTRAINT `fk_correspondence_bindings_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `correspondence_bindings` ADD CONSTRAINT `fk_correspondence_bindings_case_record` FOREIGN KEY (`case_id`, `agency_id`) REFERENCES `cases`(`id`, `agency_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `correspondence_bindings` ADD CONSTRAINT `fk_correspondence_bindings_correspondence` FOREIGN KEY (`correspondence_id`, `agency_id`) REFERENCES `correspondence`(`id`, `agency_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `correspondence_bindings` ADD CONSTRAINT `fk_correspondence_bindings_reported_item` FOREIGN KEY (`reported_item_id`, `case_id`) REFERENCES `reported_items`(`id`, `case_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `correspondence_bindings` ADD CONSTRAINT `fk_correspondence_bindings_supersedes_binding` FOREIGN KEY (`supersedes_binding_id`) REFERENCES `correspondence_bindings`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `prompt_snapshots` ADD CONSTRAINT `fk_prompt_snapshots_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `prompt_snapshots` ADD CONSTRAINT `fk_prompt_snapshots_case_record` FOREIGN KEY (`case_id`) REFERENCES `cases`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `prompt_snapshots` ADD CONSTRAINT `fk_prompt_snapshots_authority_selection` FOREIGN KEY (`authority_selection_id`, `case_id`) REFERENCES `case_authority_selections`(`id`, `case_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `prompt_snapshots` ADD CONSTRAINT `fk_prompt_snapshots_parent_binding` FOREIGN KEY (`parent_binding_id`, `case_id`) REFERENCES `correspondence_bindings`(`id`, `case_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `notice_candidates` ADD CONSTRAINT `fk_notice_candidates_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `notice_candidates` ADD CONSTRAINT `fk_notice_candidates_case_record` FOREIGN KEY (`case_id`) REFERENCES `cases`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `notice_candidates` ADD CONSTRAINT `fk_notice_candidates_prompt` FOREIGN KEY (`prompt_snapshot_id`, `case_id`) REFERENCES `prompt_snapshots`(`id`, `case_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `notice_candidates` ADD CONSTRAINT `fk_notice_candidates_parent_candidate` FOREIGN KEY (`parent_candidate_id`) REFERENCES `notice_candidates`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `validation_runs` ADD CONSTRAINT `fk_validation_runs_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `validation_runs` ADD CONSTRAINT `fk_validation_runs_candidate` FOREIGN KEY (`candidate_id`, `case_id`) REFERENCES `notice_candidates`(`id`, `case_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `validation_issues` ADD CONSTRAINT `fk_validation_issues_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `validation_issues` ADD CONSTRAINT `fk_validation_issues_run` FOREIGN KEY (`run_id`) REFERENCES `validation_runs`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `candidate_assessments` ADD CONSTRAINT `fk_candidate_assessments_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `candidate_assessments` ADD CONSTRAINT `fk_candidate_assessments_candidate` FOREIGN KEY (`candidate_id`, `case_id`) REFERENCES `notice_candidates`(`id`, `case_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `candidate_assessments` ADD CONSTRAINT `fk_candidate_assessments_supersedes_assessment` FOREIGN KEY (`supersedes_assessment_id`) REFERENCES `candidate_assessments`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `assessment_sources` ADD CONSTRAINT `fk_assessment_sources_created_by` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `assessment_sources` ADD CONSTRAINT `fk_assessment_sources_assessment` FOREIGN KEY (`assessment_id`) REFERENCES `candidate_assessments`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `assessment_sources` ADD CONSTRAINT `fk_assessment_sources_case_source` FOREIGN KEY (`case_source_id`) REFERENCES `case_sources`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `audit_events` ADD CONSTRAINT `fk_audit_events_actor` FOREIGN KEY (`actor_user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `idempotency_records` ADD CONSTRAINT `fk_idempotency_records_actor` FOREIGN KEY (`actor_user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ---------------------------------------------------------------------------------------------
-- TB MANUAL AUGMENTATION M2: CHECK constraints from the frozen preview (30).
-- Enforced by MySQL 8.4 (CHECK constraints are enforced since 8.0.16). Not represented in
-- schema.prisma; preserved by migration history, inventory and structural tests, never by db push.
-- ---------------------------------------------------------------------------------------------
ALTER TABLE `auth_sessions` ADD CONSTRAINT `ck_auth_sessions_session_time` CHECK (`expires_at` > `created_at`);
ALTER TABLE `agencies` ADD CONSTRAINT `ck_agencies_row_version` CHECK (`row_version` >= 1);
ALTER TABLE `owners` ADD CONSTRAINT `ck_owners_row_version` CHECK (`row_version` >= 1);
ALTER TABLE `legal_subjects` ADD CONSTRAINT `ck_legal_subjects_row_version` CHECK (`row_version` >= 1);
ALTER TABLE `owner_subjects` ADD CONSTRAINT `ck_owner_subjects_row_version` CHECK (`row_version` >= 1);
ALTER TABLE `signers` ADD CONSTRAINT `ck_signers_row_version` CHECK (`row_version` >= 1);
ALTER TABLE `routes` ADD CONSTRAINT `ck_routes_row_version` CHECK (`row_version` >= 1);
ALTER TABLE `mandates` ADD CONSTRAINT `ck_mandates_row_version` CHECK (`row_version` >= 1);
ALTER TABLE `mandate_versions` ADD CONSTRAINT `ck_mandate_versions_version` CHECK (`version` >= 1);
ALTER TABLE `mandate_versions` ADD CONSTRAINT `ck_mandate_versions_row_version` CHECK (`row_version` >= 1);
ALTER TABLE `mandate_coverages` ADD CONSTRAINT `ck_mandate_coverages_row_version` CHECK (`row_version` >= 1);
ALTER TABLE `coverage_signers` ADD CONSTRAINT `ck_coverage_signers_row_version` CHECK (`row_version` >= 1);
ALTER TABLE `cases` ADD CONSTRAINT `ck_cases_context_revision` CHECK (`context_revision` >= 1);
ALTER TABLE `cases` ADD CONSTRAINT `ck_cases_row_version` CHECK (`row_version` >= 1);
ALTER TABLE `reported_items` ADD CONSTRAINT `ck_reported_items_row_version` CHECK (`row_version` >= 1);
ALTER TABLE `case_works` ADD CONSTRAINT `ck_case_works_row_version` CHECK (`row_version` >= 1);
ALTER TABLE `use_mappings` ADD CONSTRAINT `ck_use_mappings_source_interval` CHECK ((`source_start_ms` IS NULL OR `source_end_ms` IS NULL OR `source_end_ms` > `source_start_ms`));
ALTER TABLE `use_mappings` ADD CONSTRAINT `ck_use_mappings_reported_interval` CHECK ((`reported_start_ms` IS NULL OR `reported_end_ms` IS NULL OR `reported_end_ms` > `reported_start_ms`));
ALTER TABLE `use_mappings` ADD CONSTRAINT `ck_use_mappings_millisecond_bounds` CHECK (COALESCE(`source_start_ms`,0) <= 9007199254740991 AND COALESCE(`source_end_ms`,0) <= 9007199254740991 AND COALESCE(`reported_start_ms`,0) <= 9007199254740991 AND COALESCE(`reported_end_ms`,0) <= 9007199254740991);
ALTER TABLE `use_mappings` ADD CONSTRAINT `ck_use_mappings_boundary_convention` CHECK (`boundary_convention` IN ('UNKNOWN','HALF_OPEN','INCLUSIVE'));
ALTER TABLE `use_mappings` ADD CONSTRAINT `ck_use_mappings_occurrence` CHECK (`occurrence` >= 1);
ALTER TABLE `use_mappings` ADD CONSTRAINT `ck_use_mappings_row_version` CHECK (`row_version` >= 1);
ALTER TABLE `source_references` ADD CONSTRAINT `ck_source_references_revision` CHECK (`revision` >= 1);
ALTER TABLE `case_sources` ADD CONSTRAINT `ck_case_sources_row_version` CHECK (`row_version` >= 1);
ALTER TABLE `case_facts` ADD CONSTRAINT `ck_case_facts_revision` CHECK (`revision` >= 1);
ALTER TABLE `prompt_snapshots` ADD CONSTRAINT `ck_prompt_snapshots_version` CHECK (`version` >= 1);
ALTER TABLE `prompt_snapshots` ADD CONSTRAINT `ck_prompt_snapshots_context_revision` CHECK (`context_revision` >= 1);
ALTER TABLE `notice_candidates` ADD CONSTRAINT `ck_notice_candidates_unsigned_only` CHECK (`signature_state` = 'HUMAN_PENDING');
ALTER TABLE `notice_candidates` ADD CONSTRAINT `ck_notice_candidates_version` CHECK (`version` >= 1);
ALTER TABLE `validation_runs` ADD CONSTRAINT `ck_validation_runs_completion_time` CHECK (`completed_at` >= `started_at`);
