// Creates the untracked root .env with random local passwords (decision D3).
// Refuses to overwrite an existing .env. Never prints secret values.
import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const target = path.join(repoRoot, '.env');

if (existsSync(target)) {
  console.error(
    `Refusing to overwrite existing ${target}. Remove it deliberately if you need new secrets.`,
  );
  process.exit(1);
}

const secret = () => randomBytes(24).toString('hex');
const root = secret();
const app = secret();
const migrate = secret();
const url = (user, password, schema) => `"mysql://${user}:${password}@127.0.0.1:3307/${schema}"`;

const content = [
  '# Local-only secrets generated by `yarn env:init`. Never commit this file.',
  `MYSQL_ROOT_PASSWORD=${root}`,
  `TB_DB_APP_PASSWORD=${app}`,
  `TB_DB_MIGRATE_PASSWORD=${migrate}`,
  `DATABASE_URL=${url('tb_dev', app, 'tb_notice_dev')}`,
  `MIGRATION_DATABASE_URL=${url('tb_migrate', migrate, 'tb_notice_dev')}`,
  `SHADOW_DATABASE_URL=${url('tb_migrate', migrate, 'tb_notice_shadow')}`,
  `TEST_DATABASE_URL=${url('tb_migrate', migrate, 'tb_notice_test')}`,
  `REPLAY_DATABASE_URL=${url('tb_migrate', migrate, 'tb_notice_replay')}`,
  '',
].join('\n');

writeFileSync(target, content, { mode: 0o600, flag: 'wx' });
console.log(`Created ${target} (mode 600). Secret values were not printed.`);
