// Pure helpers for the untracked root .env (decision D3; P1 authentication keys).
// Secret values are generated here and written only by create-env.mjs; nothing here prints them.
import { randomBytes } from 'node:crypto';

/** Exact loopback origins of the one Vite server (Windows browser uses localhost, WSL 127.0.0.1). */
export const DEFAULT_ALLOWED_WEB_ORIGINS = 'http://localhost:5173,http://127.0.0.1:5173';

const databasePassword = () => randomBytes(24).toString('hex');
const sessionSecret = () => randomBytes(32).toString('base64url');
const url = (user, password, schema) => `"mysql://${user}:${password}@127.0.0.1:3307/${schema}"`;

/** P1 keys. No database depends on them, so an unusable value may be regenerated safely. */
const P1_KEYS = [
  {
    key: 'TB_SESSION_SECRET',
    comment:
      '# P1: HMAC key for session-bound CSRF tokens (base64url, 32 random bytes). Local only.',
    value: sessionSecret,
  },
  {
    key: 'TB_ALLOWED_WEB_ORIGINS',
    comment: '# P1: exact browser origins allowed for unsafe API requests (loopback HTTP only).',
    value: () => DEFAULT_ALLOWED_WEB_ORIGINS,
  },
];

export const REQUIRED_KEYS = Object.freeze([
  'MYSQL_ROOT_PASSWORD',
  'TB_DB_APP_PASSWORD',
  'TB_DB_MIGRATE_PASSWORD',
  'DATABASE_URL',
  'MIGRATION_DATABASE_URL',
  'SHADOW_DATABASE_URL',
  'TEST_DATABASE_URL',
  'REPLAY_DATABASE_URL',
  ...P1_KEYS.map((entry) => entry.key),
]);

const assignment = (entry) => `${entry.key}=${entry.value()}`;

/** Content of a new .env with fresh random secrets. */
export function freshEnvContent() {
  const root = databasePassword();
  const app = databasePassword();
  const migrate = databasePassword();
  return [
    '# Local-only secrets generated by `yarn env:init`. Never commit this file.',
    `MYSQL_ROOT_PASSWORD=${root}`,
    `TB_DB_APP_PASSWORD=${app}`,
    `TB_DB_MIGRATE_PASSWORD=${migrate}`,
    `DATABASE_URL=${url('tb_dev', app, 'tb_notice_dev')}`,
    `MIGRATION_DATABASE_URL=${url('tb_migrate', migrate, 'tb_notice_dev')}`,
    `SHADOW_DATABASE_URL=${url('tb_migrate', migrate, 'tb_notice_shadow')}`,
    `TEST_DATABASE_URL=${url('tb_migrate', migrate, 'tb_notice_test')}`,
    `REPLAY_DATABASE_URL=${url('tb_migrate', migrate, 'tb_notice_replay')}`,
    ...P1_KEYS.flatMap((entry) => [entry.comment, assignment(entry)]),
    '',
  ].join('\n');
}

const ASSIGNMENT = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$/;

/** Keys assigned in .env content (`KEY=value` lines; comments and blank lines ignored). */
export function definedKeys(content) {
  const keys = new Set();
  for (const line of content.split('\n')) {
    const match = ASSIGNMENT.exec(line.replace(/\r$/, ''));
    if (match) keys.add(match[1]);
  }
  return keys;
}

/** Empty or an obvious placeholder (for example the `.env.example` value). */
function unusable(rawValue) {
  const value = rawValue
    .trim()
    .replace(/^(['"])(.*)\1$/, '$2')
    .trim();
  return value === '' || /REPLACE/i.test(value);
}

/**
 * Completes the P1 keys of existing .env content. A missing key is appended; an empty or
 * placeholder value is replaced in place on the line that takes effect (the last definition, as in
 * process.loadEnvFile). Every other line — including the database passwords an initialized MySQL
 * volume depends on — is kept byte for byte.
 */
export function completeP1Keys(content) {
  const lines = content.split('\n');
  const replaced = [];
  for (const entry of P1_KEYS) {
    let effective = -1;
    let value = '';
    lines.forEach((line, index) => {
      const match = ASSIGNMENT.exec(line.replace(/\r$/, ''));
      if (match && match[1] === entry.key) {
        effective = index;
        value = match[2];
      }
    });
    if (effective >= 0 && unusable(value)) {
      const carriageReturn = lines[effective].endsWith('\r') ? '\r' : '';
      lines[effective] = `${assignment(entry)}${carriageReturn}`;
      replaced.push(entry.key);
    }
  }
  let completed = lines.join('\n');
  const defined = definedKeys(content);
  const missing = P1_KEYS.filter((entry) => !defined.has(entry.key));
  if (missing.length > 0) {
    const separator = completed === '' || completed.endsWith('\n') ? '' : '\n';
    completed += `${separator}${missing.flatMap((entry) => [entry.comment, assignment(entry)]).join('\n')}\n`;
  }
  return { content: completed, added: missing.map((entry) => entry.key), replaced };
}
